baseurl = "/"
title = "Browse Theme"
languageCode = "en-us"
# theme = "github.com/onweru/browse"
theme = "browse"     # comment this out if you'ld rather use a fork of this repo or use it as a git submodule
disqusShortname = "" # Enable comments by entering your Disqus shortname
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[services]
[services.googleAnalytics]
ID = "G-MEASUREMENT_ID" # Enable Google Analytics by entering your tracking id
